### ISSUE TITLE
Austria Improvment Protocol

### ISSUE THREAD

**Issue by breitsch2** [maxkleiner/maXbox4#34]
news of 47620 VII  zapatsza
---------------------------------------
crt-alt t for help task liste
4 gewinnt update
ocean 220 in title
psi extensions with type names and so on
tee chart fixes canvas etc.
examples all files now by 402 add 3 to 405 (also trend.pas)
internalexception function
check getwebscript call 
checkversion alias to versioncheck
timesync   letsynctime function    //see up 
make xraise as keyword black font
https://github.com/P33a/SimTwo/blob/master/Editor.pas
in menu debug ? or as a function
functioncount: strings
list_functions - writeln(list_modules(exepath+'maxbox4.exe'));
procedure TFEditor.BuildRegFuncList(Sender: TPSScript);
var i, j, typ: integer;
    SaveFunclist: TStringList;
    S: string;
   -- add  funclist   procedure TFEditor.BuildRegFuncList(Sender: TPSScript);
   BuildRegFuncList(Sender);
  SynCompletionProposal.ItemList.AddStrings(FuncList);
  //SynCompletionProposal.InsertList.AddStrings(InsertList);
  SynCompletionProposal.ItemList.EndUpdate;
  //SynCompletionProposal.InsertList.EndUpdate;
  //sender.Comp.OnBeforeCleanup := @FillTypes;
  BuildRegTypeList(Sender);
  
  function FloatAsInteger(X: single): integer;
begin
  result := PInteger(@X)^;
end;

function IntegerAsFloat(X: integer): single;
begin
  result := PSingle(@X)^;
end;
  
TProcess.Create(nil); -->  Unknown identifier 'EXECUTABLE' 
Process.Executable := 'Calc.exe';
    Process.Execute;

https://github.com/P33a/SimTwo/blob/master/AStar.pas 
\maxbox3\1025_Deranged_anagrams2_mx47620.txt(160:14): Unknown identifier 'AXISLIST'

procedure LoadGridFromfile(SG: TStringGrid; fname: string);
procedure SaveGridTofile(SG: TStringGrid; fname: string);
procedure WriteVectorToGrid(SG: TStringGrid; vname: string; wval: TAffineVector);
procedure WriteStringToGrid(SG: TStringGrid; vname: string; icol: longword; wval: string);
procedure WriteFloatToGrid(SG: TStringGrid; vname: string; icol: longword; wval: double);

https://github.com/P33a/SimTwo/blob/master/Utils.pas

object SynCompletionProposal: TSynCompletion
    ItemList.Strings = (
      'Y1'
      'Y2'
      'R1'
      'R2'
      'Sek'
    )
    Position = 0
    LinesInWindow = 6
    OnSearchPosition = SynCompletionProposalSearchPosition
    SelectedColor = clHighlight
    CaseSensitive = False
    Width = 400
    ShowSizeDrag = True
    AutoUseSingleIdent = True
    ShortCut = 16416
    EndOfTokenChr = '()[]. '
    OnCodeCompletion = SynCompletionProposalCodeCompletion
    ExecCommandID = ecSynCompletionExecute
    Editor = SynEditST
    ToggleReplaceWhole = False
    Left = 192
    Top = 64
  end

procedure SetSynchroTime;
var mySTime: TIdSNTP;
begin
  mySTime:= TIdSNTP.create(self);
  try
    //mySTime.host:='0.debian.pool.ntp.org'
    mySTime.host:='pool.ntp.org'

    writeln('the internettime '+
    datetimetoStr(mystime.datetime));
    if mySTime.Synctime then
      writeln('operating system sync now!');
  finally
    mySTime.free;
    writeln('System time is now sync with the internet time '+TimeToStr(time))
  end;
end;

**Comment by breitsch2** [comment]
https://github.com/RRUZ/wmi-delphi-code-creator/tree/master/Units/Misc
https://github.com/delphidabbler/codesnip/tree/master/Src
https://github.com/fabriciocolombo/delphi-rest-client-api/tree/master/src

2022-12-15 14:45:59  UTC Compilation Timestamp
2022-12-15 15:50:51  Signtime EXE

 writeln(GETDOSOutput('powershell "Get-AuthenticodeSignature -FilePath '''+
                             exepath+'maXbox4.exe'''+' | fl *"', 'C:\'));

**Comment by maxkleiner** [comment]
Solved with news of V 47620 IX
